//! Issue #116:`collect_user_rules` 的集成测试。
//!
//! 用 `warpui::App::test` harness 把 `AIFact::Memory` 真实塞到 `ObjectStoreModel`,
//! 验证收集逻辑(过滤 trashed / 排序 / no-name 等)。harness 初始化复用
//! `data_source_tests.rs` 的样板。

use settings::manager::SettingsManager;
use warpui::{App, SingletonEntity};

use super::collect_user_rules;
use crate::ai::facts::{AIFact, AIFactObject, AIFactObjectModel, AIMemory};
use crate::auth::AuthStateProvider;
use crate::cloud_object::model::persistence::ObjectStoreModel;
use crate::cloud_object::model::view::ObjectStoreViewModel;
use crate::cloud_object::update_manager::UpdateManager;
use crate::cloud_object::{StoredObjectMetadata, StoredObjectPermissions};
use crate::notebooks::manager::NotebookManager;
use crate::server::ids::SyncId;
use crate::server_time::ServerTimestamp;
use crate::settings::AISettings;
use crate::system::SystemStats;
use crate::workspaces::user_profiles::UserProfiles;
use crate::workspaces::user_workspaces::UserWorkspaces;
use crate::NetworkStatus;

fn initialize_app(app: &mut App) {
    app.add_singleton_model(|_| NetworkStatus::new());
    app.add_singleton_model(|_| SystemStats::new());
    app.add_singleton_model(|ctx| UserWorkspaces::mock(vec![], ctx));
    app.add_singleton_model(ObjectStoreModel::mock);
    app.add_singleton_model(|ctx| UpdateManager::new(None, ctx));
    app.add_singleton_model(|_| UserProfiles::new(Vec::new()));
    app.add_singleton_model(ObjectStoreViewModel::new);
    app.add_singleton_model(NotebookManager::mock);
    app.add_singleton_model(|_| SettingsManager::default());
    app.add_singleton_model(|_| AuthStateProvider::new_for_test());
    app.update(crate::settings::init_and_register_user_preferences);
    app.update(AISettings::register_and_subscribe_to_events);
}

fn make_rule(id: i64, name: Option<&str>, content: &str, trashed: bool) -> AIFactObject {
    let sync_id = SyncId::ServerId(id.into());
    let mut metadata = StoredObjectMetadata::mock();
    if trashed {
        metadata.trashed_ts = Some(ServerTimestamp::from_unix_timestamp_micros(10).unwrap());
    }
    AIFactObject::new(
        sync_id,
        AIFactObjectModel::new(AIFact::Memory(AIMemory {
            name: name.map(str::to_string),
            content: content.to_string(),
            is_autogenerated: false,
            suggested_logging_id: None,
        })),
        metadata,
        StoredObjectPermissions::mock_personal(),
    )
}

#[test]
fn collect_user_rules_returns_empty_when_store_is_empty() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        assert!(rules.is_empty(), "空 store 应返回空 Vec, got: {rules:?}");
    });
}

#[test]
fn collect_user_rules_filters_trashed_entries() {
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        ObjectStoreModel::handle(&app).update(&mut app, |model, _| {
            for fact in [
                make_rule(1, Some("alive"), "live content", false),
                make_rule(2, Some("dead"), "should not appear", true),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        assert_eq!(rules.len(), 1, "trashed 条目应被过滤: {rules:?}");
        assert_eq!(rules[0].0.as_deref(), Some("alive"));
        assert_eq!(rules[0].1, "live content");
    });
}

#[test]
fn collect_user_rules_sorts_deterministically() {
    // 即使插入顺序乱、HashMap 迭代顺序不定,collect_user_rules 也必须给出
    // 稳定的 (name, content) 字典序输出 —— 这是 prompt cache 命中前提。
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        ObjectStoreModel::handle(&app).update(&mut app, |model, _| {
            // 故意逆序插入
            for fact in [
                make_rule(10, Some("zebra"), "z content", false),
                make_rule(11, Some("alpha"), "a content", false),
                make_rule(12, Some("mango"), "m content", false),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        let names: Vec<_> = rules.iter().filter_map(|(n, _)| n.clone()).collect();
        assert_eq!(
            names,
            vec!["alpha", "mango", "zebra"],
            "应按 name 字典序排序: {names:?}"
        );
    });
}

#[test]
fn collect_user_rules_handles_unnamed_rules() {
    // None < Some 在 Rust PartialOrd 下成立,无 name 的条目应排到最前。
    App::test((), |mut app| async move {
        initialize_app(&mut app);
        ObjectStoreModel::handle(&app).update(&mut app, |model, _| {
            for fact in [
                make_rule(1, Some("named"), "named content", false),
                make_rule(2, None, "unnamed content", false),
            ] {
                model.add_object(fact.id, fact);
            }
        });

        let rules = app.read(|app| collect_user_rules(ObjectStoreModel::as_ref(app)));
        assert_eq!(rules.len(), 2);
        assert_eq!(rules[0].0, None, "无 name 条目应排在前: {rules:?}");
        assert_eq!(rules[0].1, "unnamed content");
        assert_eq!(rules[1].0.as_deref(), Some("named"));
    });
}
